### ISSUE TITLE
First version of the pipeline

### ISSUE THREAD

**Issue by manulera** [manulera/genestorian_data_refinement#16]
This first version should have the following:

* [x] Formatting for the Dey lab strains:
  * A python script in `Lab_strains/dey_lab/format.py` that takes `Manu_strains.xlsx` as an input and returns a file `Lab_strains/dey_lab/strains.tsv` in which the first column is the id of the strain `e.g.GD172` and the second column is the phenotype.
* [x] Replacing allele names in the Dey lab collection:
  * A python script that:
    * Takes `Lab_strains/dey_lab/strains.tsv` and `data/alleles.toml` as an input and replaces the allele names by the word `ALLELE` and prints all the substituted genotypes to a text file, one per line.
    * For now, no need to format this output, we can do it in next iterations.

You can push your code after the first task, so that I can review it already, and then the second one.

**Comment by manulera** [comment]
Remember to reference the PR or commit where you add these changes

**Comment by anamika-yadav99** [comment]
closed with pr #20

**Comment by manulera** [comment]
See #20

**Comment by anamika-yadav99** [comment]
@manulera This is the full scipt : https://github.com/manulera/genestorian_data_refinement/blob/gsoc2022/Lab_strains/dey_lab/format.py

**Comment by manulera** [comment]
Hello @anamika-yadav99 it still does not do what it is supposed to do. I flagged this in #20 (comment quoted below)

> Lab_strains/dey_lab/format.py no longer solves https://github.com/manulera/genestorian_data_refinement/issues/16 you should revert to this version: https://github.com/manulera/genestorian_data_refinement/commit/97a4d5b118e15a774e2e717af16efd7001acc843

You marked it as complete, please carefully read my feedback and do not mark the tasks as resolved if they are not.

**Comment by manulera** [comment]
Good job! Almost perfect. Two things you can do to make things a bit better, and then we close this issue:

* [ ] You are going to use the functions `feature_dict` and `replace_allele_features` in multiple scripts. Instead of copy pasting them in every file (bad practice), move them to the module file so you can simply import them. Also, `feature_dict` is a bad function name, it looks like a variable, put a verb in the function name to make it more obvious that it is a function, e.g. `make_feature_dict`, `create_feature_dict` or something like that.
* [ ] You are no longer using generalised_function.py, remove this file
* [ ] Remove the copied functions from `generalised_functions.py`, and import them from the module instead (see first task in this list).
* [ ] When you run the `first_version_pipeline.py` script, look at lines 106 and 107 of `first_version_pipeline.txt`. Check the same lines in `strains.tsv`. This case should be handled.

Almost there!

**Comment by manulera** [comment]
Ah, another thing:

* [ ] Note that in some lines in `strains.tsv` (such as 222), there is a weird set of characters (`‚àÜ0`), this gives some problems later, specially when you want to convert to json see that in json this becomes `\u201a\u00e0\u00dc`. There is also `Œî` somewhere. These characters seem to be wrong encodings for delta (Δ). Replace them by Δ in `format.py`.

**Comment by anamika-yadav99** [comment]
- [ ] kan, nat, hph etc (anything in synonyms section of marker isn't replaced by word 'MARKER')

**Comment by manulera** [comment]
* [ ] In `format.py`, you should not print the index in the first column (when calling `read_file.to_csv`).

**Comment by anamika-yadav99** [comment]
> Ah, another thing:
> 
> * [ ]  Note that in some lines in `strains.tsv` (such as 222), there is a weird set of characters (`‚àÜ0`), this gives some problems later, specially when you want to convert to json see that in json this becomes `\u201a\u00e0\u00dc`. There is also `Œî` somewhere. These characters seem to be wrong encodings for delta (Δ). Replace them by Δ in `format.py`.
Should I replace just àÜ0 with delta or any such weird character with delta?

**Comment by manulera** [comment]
For now, just replace those two occurrences by delta (`‚àÜ0` and `Œî`)

**Comment by manulera** [comment]
What I meant here
> Remove the copied functions from generalised_functions.py, and import them from the module instead (see first task in this list).

Is to remove the repeated functions from `first_version_pipeline.py`

**Comment by anamika-yadav99** [comment]
> What I meant here
> 
> > Remove the copied functions from generalised_functions.py, and import them from the module instead (see first task in this list).
> 
> Is to remove the repeated functions from `first_version_pipeline.py`

Should I move the function to the genestorian_module and then import it?

**Comment by anamika-yadav99** [comment]
completed with PR#23
