### ISSUE TITLE
Small API

### ISSUE THREAD

**Issue by manulera** [manulera/genestorian_data_refinement#40]
HI @anamika-yadav99, I am thinking to pick up on the project in a few weeks, and I think it would be nice to have a simple web interface to quickly show in the web browser what the pipeline does.

The first step towards that is making an API entrypoint where the user would make a request with the allele name, and get back the json of the pattern. For example:

User input:

```json
{
  "name": "cut11-mch:ura4+"
}
```

Response:

```json
{
  "name": "cut11-mch:ura4+",
  "pattern": [
      ["GENE", ["cut11"]],
      ["-", ["-"]],
      ["TAG", ["mch"]],
      ["-", [":"]],
      ["ALLELE", ["ura4+"]]
    ]
}
```

This is relatively easy to do using FastAPI. I have made a file to run the API, so that you only have to write a function that takes the allele name and returns the pattern, and that should work. Your function would have to be called here:

https://github.com/manulera/genestorian_data_refinement/blob/5d64d6e69402b51c0d4a67959b50bbbcecabfe94/api.py#L37-L57

Where it says `your_function`.

You can run the api in your computer very easily and try the dummy request following these instructions:

## Install dependencies

The easiest would be to clone the repo again, I think:

```
git clone https://github.com/manulera/genestorian_data_refinement
git checkout -b api
git pull origin api
```

Then install dependencies and activate environment
```
poetry install
poetry shell
```

Remember also to download the necessary files (see https://github.com/manulera/genestorian_data_refinement#strain-lists)

## Running and using the API

To run the API locally:

```
uvicorn api:app --reload
```

The you go to http://127.0.0.1:8000/ and you should see the api documentation, where you can make a test request. Go to `/process_allele` and click on `try it out`. This will allow you to add an example json, by default the one from above. Then you click on the "execute" button and you should see the `Response body`, which is what the function `check_allele` returns.

## What to do

Replace the function `your_function` by a function that takes the allele name and returns the pattern, and see if it works when you make a request from the api.

**Comment by riddhisera** [comment]
Hi @manulera!

I'm Riddhi Sera, a computational biology enthusiast. I found this repo on the GSOC 2022 website and have been following it for the past few weeks.

I was able to write the function you requested using the `build_nltk_tag` function from `genestorian_module/build_nltk_tags.py`, although it involved making some changes to the `build_nltk_tag.py` file as well. 

I would be happy to work on this issue and contribute to the project. Please let me know if there is anything else I should be aware of, or if there are any guidelines for contributing to the project.

Thank you for your time and consideration. I look forward to hearing from you soon!

**Comment by anamika-yadav99** [comment]
Hi @riddhisera can you please create a PR if you have already worked on the issue? We can assist you better if we can look into the code.

**Comment by riddhisera** [comment]
Thanks, @anamika-yadav99! I have created the PR at #41.

**Comment by manulera** [comment]
Merged into master, thanks @riddhisera !
